# Generated by Django 4.1.7 on 2023-04-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(default="", upload_to="media/"),
            preserve_default=False,
        ),
    ]
