# Generated by Django 4.1.7 on 2023-03-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nni",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.BigIntegerField(unique=True),
        ),
    ]
