# Generated by Django 4.1.7 on 2023-04-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nni",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
