# Generated by Django 4.1.7 on 2023-04-28 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("loan_status", models.CharField(max_length=50)),
                ("loan_start_date", models.DateField(default=datetime.datetime.now)),
                ("loan_end_date", models.DateField()),
                ("repayment_method", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Success", "Success"),
                            ("Confirmed", "Confirmed"),
                            ("Refused", "Refused"),
                        ],
                        default="Pending",
                        max_length=32,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.bank",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adminstrator",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bank",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.bank",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("users.customuser",),
        ),
    ]
