# Generated by Django 4.1.7 on 2023-04-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=2)),
                ("loan_status", models.CharField(max_length=50)),
                ("loan_start_date", models.DateField()),
                ("loan_end_date", models.DateField()),
                ("repayment_method", models.CharField(max_length=50)),
            ],
        ),
    ]
