# Generated by Django 4.1.7 on 2023-04-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="client",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.client",
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.admin"
            ),
        ),
    ]
