# Generated by Django 4.1.7 on 2023-04-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="borrower",
        ),
    ]
