# Generated by Django 4.1.7 on 2023-04-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Adminstrator",
        ),
    ]
