# Generated by Django 4.1.7 on 2023-04-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_rename_responsable_bank_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="bank",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.bank",
            ),
            preserve_default=False,
        ),
    ]
