# Generated by Django 4.1.7 on 2023-04-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_loan_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="state",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Confirmed", "Confirmed"),
                    ("Refused", "Refused"),
                ],
                default="Pending",
                max_length=32,
            ),
        ),
    ]
