# Generated by Django 4.1.7 on 2023-04-27 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_loan_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loan_start_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
